name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest]
        arch: [x64, arm64]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Setup architecture
        env:
          ARCH_VALUE: ${{ matrix.arch }}
        run: echo "ARCH=$ARCH_VALUE" >> $GITHUB_ENV

      - name: Determine runtime identifier
        run: |
          if [[ "${{ matrix.platform }}" == "macos-latest" ]]; then
            if [[ "${{ matrix.arch }}" == "arm64" ]]; then
              echo "RID=osx-arm64" >> $GITHUB_ENV
            else
              echo "RID=osx-x64" >> $GITHUB_ENV
            fi
          else
            if [[ "${{ matrix.arch }}" == "arm64" ]]; then
              echo "RID=linux-arm64" >> $GITHUB_ENV
            else
              echo "RID=linux-x64" >> $GITHUB_ENV
            fi
          fi

      - name: Build project
        run: dotnet publish -c Release -r $RID --self-contained true -o ./publish

      - name: Create archive
        run: |
          mkdir -p release
          tar -czf release/rcurl-${{ matrix.platform == 'macos-latest' && 'macos' || 'linux' }}-${{ matrix.arch }}.tar.gz -C publish .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rcurl-${{ matrix.platform == 'macos-latest' && 'macos' || 'linux' }}-${{ matrix.arch }}
          path: release/rcurl-*.tar.gz

  release:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Download macos arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: rcurl-macos-arm64
          path: release

      - name: Download macos x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: rcurl-macos-x64
          path: release

      - name: Download linux arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: rcurl-linux-arm64
          path: release

      - name: Download linux x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: rcurl-linux-x64
          path: release

      - name: List release files
        run: ls -l release

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: release/*.tar.gz